version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cafe_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    command: ["bash", "-c", "docker-entrypoint.sh postgres && psql -U postgres -c 'CREATE DATABASE cafe_db;' && wait"]

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_NAME: cafe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
