# Generated by Django 5.1.6 on 2025-02-12 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'в ожидании'), ('ready', 'готово'), ('paid', 'оплачено')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
